#!/bin/bash

# CodeDeplpy Notification
# ========================
cd /opt/codedeploy-agent/deployment-root/[DEPLOYMENT_GROUP_ID]/$DEPLOYMENT_ID/deployment-archive/scripts/codedeploy-pushnotification
sudo composer update
sudo php deployment-start.php